// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"HGGdCnf","status":true,"description":"Guard Skill Confirmation by c2h6o for Hanabi Gakuen","parameters":{}},
{"name":"HGDlyMxPp","status":true,"description":"Daily maximum prop limit","parameters":{}},
{"name":"HGSpItm","status":true,"description":"Equipment Rarity Enhancement Card by c2h6o for Hanabi Gakuen","parameters":{}},
{"name":"YEP_MessageCore","status":true,"description":"v1.02 Adds more features to the Message Window to customized\nthe way your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward":"Input.isPressed('pagedown')","Word Wrapping":"false","Description Wrap":"false","---Font---":"","Font Name":"GameFont","Font Size":"28","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]"}},
{"name":"HGPlgCore","status":true,"description":"Core of plugins by c2h6o for Hanabi Gakuen","parameters":{"localTesting":"0"}},
{"name":"HGSkEffExt","status":true,"description":"Skill Effect Extension by c2h6o for Hanabi Gakuen","parameters":{}},
{"name":"HGSkEqpRel","status":true,"description":"Relationships of Skills & Equipments by c2h6o for Hanabi Gakuen","parameters":{}},
{"name":"HGSkLn","status":true,"description":"Skill learning by c2h6o for Hanabi Gakuen","parameters":{}},
{"name":"HGEqpGft","status":true,"description":"Gifts of Equipments by c2h6o for Hanabi Gakuen","parameters":{}},
{"name":"YEP_SkillCore","status":true,"description":"v1.00 Skills are now given more functions and the ability to\r\nrequire different types of costs.","parameters":{"---General---":"","Cost Padding":"4","Command Alignment":"center","---HP Costs---":"","HP Format":"%1%2","HP Font Size":"20","HP Text Color":"18","HP Icon":"162","---MP Costs---":"","MP Format":"%1%2","MP Font Size":"20","MP Text Color":"23","MP Icon":"165","---TP Costs---":"","TP Format":"%1%2","TP Font Size":"20","TP Text Color":"29","TP Icon":"164"}},
{"name":"YEP_X_SkillCooldowns","status":true,"description":"v1.01 (Requires YEP_SkillCore.js) Cooldowns can be applied\r\nto skills to prevent them from being used continuously.","parameters":{"---Cooldown---":"","Cooldown Format":"%1CD","Cooldown Font Size":"20","Cooldown Text Color":"6","Cooldown Icon":"75","Cooldown After Battle":"-100","Cooldown Steps":"5","Cooldown Bypass":"","---Warmup---":"","Warmup Format":"%1WU","Warmup Font Size":"20","Warmup Text Color":"4","Warmup Icon":"75"}},
{"name":"NameInput","status":true,"description":"名字输入","parameters":{}},
{"name":"HGSkipLdLst","status":true,"description":"Skip loading list, load the first save","parameters":{}},
{"name":"HGParMax","status":true,"description":"","parameters":{}}
];
